CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
	id UUID UNIQUE NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
	email TEXT UNIQUE NOT NULL,
	provider TEXT NOT NULL,
	picture TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS series (
	id UUID UNIQUE NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
	name TEXT UNIQUE NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS comics (
	id UUID UNIQUE NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
	series_id UUID REFERENCES series (id) ON DELETE CASCADE,
	name TEXT UNIQUE NOT NULL,
	thumbnail TEXT NOT NULL DEFAULT '',
	url TEXT NOT NULL DEFAULT '',
	released_at TIMESTAMPTZ NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_series (
	id UUID UNIQUE NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
	user_id UUID REFERENCES users (id) ON DELETE CASCADE,
	series_id UUID REFERENCES series (id) ON DELETE CASCADE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
